#!/bin/bash
echo  "Upando SOREX_izing. Por favor, espere."
cd  ~
cd /home/deploy/sorex
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all

echo  "Deu tudo certo, xapa!"
